header = "// SPDX-License-Identifier: MIT"
sys_includes = ["stddef.h", "stdint.h", "stdlib.h"]
no_includes = true
include_guard = "AV_METRICS"
tab_width = 4
style = "Type"
language = "C"

[export]
prefix = "AVM"
